### PR TITLE
Adding eBook Sample to repository CI pipeline

### PR DESCRIPTION
**Pull request by raymondliu2022**

### CODE REVIEW

**Comment by raymondliu2022** [comment]
Resolves issue #9

**Comment by CesarValiente** [comment]
LGTM! @raymondliu2022 please address conflicts and we can merge this PR :-) Thanks!

**Comment by raymondliu2022** [comment]
@CesarValiente Hopefully this does the trick

**Comment by CesarValiente** [comment]
Thanks for doing this @raymondliu2022 hope you have a great rest of the summer!! :-D

**Review by CesarValiente — APPROVED** [review]
LGTM! Thanks Raymond!

**Pull request merged**
